db:
  host: 'localhost'
  username: 'postgres'
  password: 'postrgres'
  synchronize: true

refreshjwt: 
  secret: 'Development_Access_Token_Secret'

accessjwt:
  secret: 'Development_Refresh_Token_Secret'

passwordResetJwt:
  secret: 'Development_Password_Reset_Token_Secret'